### ISSUE TITLE
Valgrind: "Dwarf2 reader: badly formed extended line op encountered" messages flooding output

### ISSUE THREAD

**Issue by SpencerFleming** [BoiseState-AdaptLab/adapt-lidar-tools#246] opened 2019-07-24 04:12 UTC
This has been happening for a while and isn't a critical issue but I think it should be looked into. When Valgrind is run on our code, it will produce hundreds of lines that say "dwarf2 reader: badly formed extended line op encountered". It makes reading the output require a lot of scrolling. Supposedly this means that either Valgrind is reading the code wrong, or we're not producing debug information correctly.

This makes me wonder if we even have debugging flags in our makefile right now.

**Comment by jaredwhite547** [comment] 2020-04-23 18:44
Can't reproduce, and haven't noticed before. Closing.

**Closed by jaredwhite547** 2020-04-23 18:44 UTC
Labels: bug, question

**Comment by dufferzafar** [comment] 2022-07-03 20:36
I'm seeing the same issue. when I ran `valgrind --tool callgrind` on our app, it spew out lots of `==2381658== Warning: DWARF2 reader: Badly formed extended line op encountered` errors

**Comment by dufferzafar** [comment] 2022-10-04 05:48
@jaredwhite547 Is there any more debugging information I could provide that would help with this?

**Comment by max0x7ba** [comment] 2025-12-08 17:39
I've experienced this warning for a decade too.

Operating System: KDE neon User Edition
KDE Plasma Version: 6.5.3
KDE Frameworks Version: 6.20.0
Qt Version: 6.10.1
Kernel Version: 6.8.0-88-generic (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5825U with Radeon Graphics
Memory: 64 GiB of RAM (62.2 GiB usable)
Graphics Processor: AMD Radeon Graphics
Manufacturer: Dell Inc.
Product Name: Inspiron 14 7425 2-in-1
System Version: 1.23.0
